FROM crops/poky:debian-11

ENV DEBIAN_FRONTEND=noninteractive

USER root
RUN apt-get install -y python3-pip

# Install yocto cooker build system
RUN pip3 install 'git+https://github.com/cpb-/yocto-cooker.git@master'

RUN ["/bin/bash"]
